In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
import xgboost as xgb
import util
import numpy as np

In [5]:
data_df = pd.read_csv("C:\\Users\\dinur\\OneDrive\\Desktop\\ML-Backend\\assets\\all_07_07_23.csv")

In [10]:
l = data_df.loc[data_df['Image ID']=='C.10.12.5']

In [14]:
l.shape[0]

1

In [16]:
data_df["Age"] = data_df["Age"].fillna(method='ffill')

In [2]:
ent = util.findEntry('C.10.12.5')

In [3]:
ent

Image ID New Image ID Pt Registration no Folder no Age  Gender Smoking  \
1154  C.10.12.5    C-10-12-5                NaN        10  26  Female      no   

     Chewing Betel Quid  Alcohol Clinical diagnosis   ...  \
1154                  no      no                 NaN  ...   

     Histopathological disgnosis Medication history  \
1154                         NaN                NaN   

     History of presenting complaint Duration of practising habits, if any  \
1154                             NaN                                   NaN   

     Medical history Oral hygiene product used Comments  \
1154             NAD                       NaN      NaN   

     Image Category (OCA/ OPMD/ Benign/ Healthy) visible lesion present/ not  \
1154                                      normal                         NaN   

     location of the mouth  
1154                   NaN  

[1 rows x 24 columns]

In [4]:
ent.columns

Index(['Image ID', 'New Image ID', 'Pt Registration no', 'Folder no', 'Age',
       'Gender', 'Smoking', 'Chewing Betel Quid ', 'Alcohol',
       'Clinical diagnosis ', 'Image captured by',
       'Clinical presentation of the lesion', 'Chief complaint',
       'Other investigations/tests', 'Histopathological disgnosis',
       'Medication history', 'History of presenting complaint',
       'Duration of practising habits, if any', 'Medical history',
       'Oral hygiene product used', 'Comments',
       'Image Category (OCA/ OPMD/ Benign/ Healthy)',
       'visible lesion present/ not', 'location of the mouth'],
      dtype='object')

In [3]:

null_rem = util.nullRemoval(ent)
cleaned = util.dataCleaning(null_rem)
x = util.dataProcessing(cleaned)
head = x.head(1)
    

values = head.values

dmatrix = xgb.DMatrix(values)


In [13]:
values

array([[26, 0, True, False, False, False, True, False, False, False,
        True, False, False, True, False, False]], dtype=object)

In [4]:
cleaned.head()

Age  Gender     Smoking Chewing Betel Quid      Alcohol  \
0   26  Female          no                  no          no   
1   35    Male         yes                 yes         yes   
2   35     pns          ex                  ex  occational   
3   35  Female          no                  no          no   
4   35    Male  occational          occational         yes   

   Clinical diagnosis  Image Category (OCA/ OPMD/ Benign/ Healthy)  
0                    0                                      normal  
1                    0                                         NaN  
2                    0                                         NaN  
3                    0                                         NaN  
4                    0                                         NaN

In [5]:
x.head()

Age  Clinical diagnosis   Gender_Female  Gender_Male  Gender_pns  \
0   26                    0           True        False       False   
1   35                    0          False         True       False   
2   35                    0          False        False        True   
3   35                    0           True        False       False   
4   35                    0          False         True       False   

   Smoking_ex  Smoking_no  Smoking_occational  Smoking_yes  \
0       False        True               False        False   
1       False       False               False         True   
2        True       False               False        False   
3       False        True               False        False   
4       False       False                True        False   

   Chewing Betel Quid _ex  Chewing Betel Quid _no  \
0                   False                    True   
1                   False                   False   
2                    True                   False   
3                   False                    True   
4                   False                   False   

   Chewing Betel Quid _occational  Chewing Betel Quid _yes  Alcohol_no  \
0                           False                    False        True   
1                           False                     True       False   
2                           False                    False       False   
3                           False                    False        True   
4                            True                    False       False   

   Alcohol_occational  Alcohol_yes  
0               False        False  
1               False         True  
2                True        False  
3               False        False  
4               False         True

In [6]:
cleaned.head()

Age  Gender     Smoking Chewing Betel Quid      Alcohol  \
0   26  Female          no                  no          no   
1   35    Male         yes                 yes         yes   
2   35     pns          ex                  ex  occational   
3   35  Female          no                  no          no   
4   35    Male  occational          occational         yes   

   Clinical diagnosis  Image Category (OCA/ OPMD/ Benign/ Healthy)  
0                    0                                      normal  
1                    0                                         NaN  
2                    0                                         NaN  
3                    0                                         NaN  
4                    0                                         NaN

In [7]:
x.head()

Age  Clinical diagnosis   Gender_Female  Gender_Male  Gender_pns  \
0   26                    0           True        False       False   
1   35                    0          False         True       False   
2   35                    0          False        False        True   
3   35                    0           True        False       False   
4   35                    0          False         True       False   

   Smoking_ex  Smoking_no  Smoking_occational  Smoking_yes  \
0       False        True               False        False   
1       False       False               False         True   
2        True       False               False        False   
3       False        True               False        False   
4       False       False                True        False   

   Chewing Betel Quid _ex  Chewing Betel Quid _no  \
0                   False                    True   
1                   False                   False   
2                    True                   False   
3                   False                    True   
4                   False                   False   

   Chewing Betel Quid _occational  Chewing Betel Quid _yes  Alcohol_no  \
0                           False                    False        True   
1                           False                     True       False   
2                           False                    False       False   
3                           False                    False        True   
4                            True                    False       False   

   Alcohol_occational  Alcohol_yes  
0               False        False  
1               False         True  
2                True        False  
3               False        False  
4               False         True

In [7]:
x.dtypes

Age                               int32
Clinical diagnosis                int32
Gender_Female                      bool
Gender_Male                        bool
Gender_pns                         bool
Smoking_ex                         bool
Smoking_no                         bool
Smoking_occational                 bool
Smoking_yes                        bool
Chewing Betel Quid _ex             bool
Chewing Betel Quid _no             bool
Chewing Betel Quid _occational     bool
Chewing Betel Quid _yes            bool
Alcohol_no                         bool
Alcohol_occational                 bool
Alcohol_yes                        bool
dtype: object

In [10]:
x.head(1)

Age  Clinical diagnosis   Gender_Female  Gender_Male  Gender_pns  \
0   26                    0           True        False       False   

   Smoking_ex  Smoking_no  Smoking_occational  Smoking_yes  \
0       False        True               False        False   

   Chewing Betel Quid _ex  Chewing Betel Quid _no  \
0                   False                    True   

   Chewing Betel Quid _occational  Chewing Betel Quid _yes  Alcohol_no  \
0                           False                    False        True   

   Alcohol_occational  Alcohol_yes  
0               False        False

In [3]:
pred = util.metaPredict(ent)

In [14]:
probabilities = np.exp(pred) / np.exp(pred).sum()
oca, opmd, benign, healthy = probabilities.tolist()[0]

In [11]:
(probabilities)

array([[2.2572964e-05, 9.1330126e-05, 8.1083889e-04, 9.9907523e-01]],
      dtype=float32)

In [5]:
pred

array([[-4.634688 , -3.23696  , -1.0533713,  6.0631447]], dtype=float32)

In [17]:
meta_prob_3 = np.array([oca+opmd, benign, healthy], dtype=float)

In [18]:
meta_prob_3

array([1.13903090e-04, 8.10838887e-04, 9.99075234e-01])

In [ ]:
weighted_avg_probs = (model1_probs * weights[0]) + (model2_probs * weights[1])

In [19]:
arr = np.array([1,2,3])
arr1 = np.array([2, 1, 5])
arr*arr1

array([ 2,  2, 15])

In [20]:
arr[0]

1